services:
  flask_api:
    build: ./python_api
    container_name: python_api
    ports:
      - "5000:5000"
    volumes:
      - "./python_api:/app"
    command: "python app.py"

  mysql_db:
    image: mysql:8.0
    environment:
      MYSQL_USER: root
      MYSQL_POST: mysql_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: flaskdb
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  app_network:
    driver: bridge